### ISSUE TITLE
Even if I Like the page I'm unable to see the content

### ISSUE THREAD

**Issue by mungle** [marcelkalveram/facebook-tab-boilerplate#3]
Hello!
I'm using your boilerplate to add a tab in my facebook page. Everything it works but (as the title say) even if I like my page it appears "You are not a fun".

I saw your plugin is 2 years old. Does FB changed something and your script doesn't work with new versions of FB?
Thank you!

**Comment by marcelkalveram** [comment]
I assume you've put in the correct application ID and secret.
I'll have a look into that and see if anything has changed in the meantime.

**Comment by marcelkalveram** [comment]
Looks like the whole process of setting up Facebook apps has been changed, and there is a new connect SDK. I'd have to look into that or set up a new boilerplate, so I would consider this repository obsolete.
